#! /bin/bash

clear
# Variables de color de script
#
ROJO="\033[1;31m"
NORMAL="\033[0m"
AZUL="\033[1;34m"

# Este script funciona en Ubuntu 18.04, bionic y Ubuntu 20.04. Para Linux Mint cambie la variable por bionic o focal, según corresponda:
#
	#DISTRO=focal
	#DISTRO=bionic
	DISTRO=$(lsb_release -cs)
	echo ""	
	echo "Solicitando contraseña del usuario con derechos de administrador"
	echo ""
	echo "Asking password of the user with administrations rights"
	echo ""
	sudo echo ""

# Borrando antiguos archivos de smartdre o lliurex-smart
#

# Instalar docker
#


	sudo apt update
	sudo apt install -f
	sudo apt-get install apt-transport-https ca-certificates curl gnupg-agent software-properties-common -y
	sudo apt install -f
	sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
	#sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $DISTRO stable"
	touch docker.list
	echo "deb [arch=amd64] https://download.docker.com/linux/ubuntu $DISTRO stable" > docker.list
	sudo mv docker.list /etc/apt/sources.list.d/docker.list
	sudo apt-key fingerprint 0EBFCD88
	sudo apt update
	sudo apt install docker-ce docker-ce-cli containerd.io -y 
	#sudo usermod -aG docker $USER
	sudo rm /etc/apt/sources.list.d/docker.list

# Hacer la aplicación iniciable en cada reinicio y usable para cualquier usuario sin "sudo"
#
	sudo cp smartdre /usr/bin
    	sudo chmod +x /usr/bin/smartdre
    	sudo chown root:root zz-smartdre
    	sudo chmod 0440 zz-smartdre
    	sudo cp zz-smartdre /etc/sudoers.d/ 
    	sudo cp smartdre.desktop /etc/xdg/autostart/
    	sudo cp smartdre.desktop /usr/share/applications/


# Notificaciones al terminar
#
	echo ""
	echo "Reinicie el equipo para que se ejecute la aplicación"
	echo ""
	sudo notify-send "Reinicie el equipo para que se ejecute la aplicación"







