#! /bin/bash

# Install docker

# Variable distribución, esta muestra la distribución necesaria para instalar docker

#distribucion=$(lsb_release -cs)

# Este script funciona en Ubuntu 18.04, bionic. Para Mint 20, cambiar por la siguiente:

distribucion=bionic

echo $distribucion
#sudo apt update
sudo apt install -f
sudo apt-get install apt-transport-https ca-certificates curl gnupg-agent software-properties-common -y
sudo apt install -f
sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
#sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $distribucion stable"
touch docker.list
echo "deb [arch=amd64] https://download.docker.com/linux/ubuntu $distribucion stable" > docker.list
sudo mv docker.list /etc/apt/sources.list.d/docker.list
sudo apt-key fingerprint 0EBFCD88
sudo apt update
sudo apt install docker-ce docker-ce-cli containerd.io -y
sudo usermod -aG docker $USER


# Descarga e instala el driver táctil de la pizarra en el sistema anfitrión
# Paquetes nwfermi y xf86-input-nextwindow

FILE1=nwfermi-module_0.6.5.1-0+lliurex6_amd64.deb
FILE2=nwfermi-daemon_0.6.5.1-0+lliurex6_amd64.deb
FILE3=xf86-input-nextwindow_0.3.4~lliurex1+focal_amd64.deb

if [ -f "$FILE1" ]; then
    echo "$FILE1 exist."
else
    wget https://github.com/aosucas499/nwfermi/raw/main/bionic/amd64/nwfermi-module_0.6.5.1-0%2Blliurex6_amd64.deb
fi


if [ -f "$FILE2" ]; then
    echo "$FILE2 exist."
else
    wget https://github.com/aosucas499/nwfermi/raw/main/bionic/amd64/nwfermi-daemon_0.6.5.1-0%2Blliurex6_amd64.deb
fi


if [ -f "$FILE3" ]; then
    echo "$FILE3 exist."
else
    wget https://github.com/aosucas499/nwfermi/raw/main/bionic/amd64/xf86-input-nextwindow_0.3.4%7Elliurex1%2Bfocal_amd64.deb
fi



sudo dpkg -i $FILE1
sudo apt install -f
sudo dpkg -i $FILE2
sudo apt install -f
sudo dpkg -i $FILE3

sudo apt install -f

echo ""
echo "Ejecute la app o script smartdre para que se ejecute el docker"
echo ""


