#! /bin/bash

clear
# Variables 
#
ROJO="\033[1;31m"
NORMAL="\033[0m"
AZUL="\033[1;34m"
DISTRO=$(lsb_release -cs)
DESKTOP=$XDG_CURRENT_DESKTOP
	
# Borrando antiguos archivos de smartdre o lliurex-smart
#
	echo ""	
	echo -e "${ROJO}Borrando si existen archivos de anteriores instalaciones${NORMAL}"
	echo ""
	echo -e "${ROJO} Deleting if there are files from previous installations${NORMAL}"
	echo ""
	sudo chmod +x uninstall-smartdre
	sudo ./uninstall-smartdre


# Comprueba está instalado smartboard del cga
#
	sudo apt update -y
		if dpkg-query --list | grep smartboard-meta; then
        		echo "Smartboard eos instalado"
			
		else
			echo "Smartboard EOS no instalado"
			notify-send "Smartboard EOS no instalado"
			zenity --info \
       			--title="Smartboard EOS no instalado" \
      			--width=500 \
		        --text="Instalando respositorios dede <b>SmartBoard</b> e instalando Drivers"
			wget https://downloads.smarttech.com/software/linux/nb-for-ubuntu-20/dists/swbuild.asc
			gpg --show-keys --fingerprint swbuild.asc
			sudo apt-key add swbuild.asc
			touch smartboard.list
			echo "deb http://downloads01.smarttech.com/software/linux/nb-for-ubuntu-20 stable non-free" > smartboard.list
			sudo mv smartboard.list /etc/apt/sources.list.d/smartboard.list
			sudo apt-get update -y
			sudo apt-get install smart-product-drivers smart-notebook -y
			sudo apt install -f -y
			sudo rm /etc/apt/sources.list.d/smartboard.list
			sudo rm swbuild.asc
		fi

#Instalación paquetes/drivers nwfermi en el sistema host
#
		sleep 4
		sudo apt update -y
		sudo apt-get install git -y
		sudo apt-get install dkms build-essential autoconf xutils-dev libtool xserver-xorg-dev libc6-i386 pkg-config evtest -y
		#sudo cp custom.conf /etc/gdm3/
		git clone https://github.com/aosucas499/nwfermi-ubuntu22.04
		cd nwfermi*
		echo "Instalando drivers NWFERMI"
		notify-send "Instalando drivers NWFERMI"
		zenity --info \
       		--title="Instalando drivers NWFERMI" \
      		--width=500 \
		--text="Drivers necesarios para el model <b>Smartboard 480</b>"
  sudo apt-get purge --remove nwfermi-daemon -y
  sudo apt-get purge --remove nwfermi-module -y
  sudo apt-get purge --remove nwfermi-module-host -y
  sudo apt-get purge --remove nwfermi-module-host-pointer -y
  sudo apt-get purge --remove xf86-input-nextwindow -y
		sudo dkms uninstall nwfermi/0.6.5.0 
		sudo cp -p -r usr/src/nwfermi-0.7.0.1 /usr/src
		sudo dkms build nwfermi/0.7.0.1
		sudo dkms install nwfermi/0.7.0.1
		sudo mkdir -p /etc/X11/xorg.conf.d
		sudo cp etc/X11/xorg.conf.d/10-nwfermi.conf /etc/X11/xorg.conf.d/
		sudo cp etc/X11/xorg.conf.d/10-nwfermi.conf /usr/share/X11/xorg.conf.d/
		sudo cp usr/sbin/nwfermi_daemon /usr/sbin
		sudo cp etc/udev/rules.d/40-nw-fermi.rules /etc/udev/rules.d/
		sudo cp etc/systemd/system/nwfermi@.service /etc/systemd/system/
		sudo systemctl daemon-reload
		#sudo apt install xutils-dev -y
		#export XORG_CFLAGS="-I/usr/include/xorg -I/usr/include/X11"
		#export XORG_LIBS="-L/usr/lib/xorg -L/usr/lib/X11"
		#cd usr/src/xf86-input-nextwindow-0.3.4
		#chmod +x autogen.sh ; ./autogen.sh
		#sudo make
		#sudo make install
		#sudo cp /usr/local/lib/xorg/modules/input/nextwindow_drv.* /usr/lib/xorg/modules/input/
		wget https://github.com/aosucas499/nwfermi/raw/refs/heads/main/focal/xf86-input-nextwindow_0.3.4~lliurex1+focal2_amd64.deb
		sudo dpkg -i xf86-input-nextwindow_0.3.4~lliurex1+focal2_amd64.deb
		sudo rm xf86-input-nextwindow_0.3.4~lliurex1+focal2_amd64.deb
		sudo groupadd input
		sudo useradd gdm 
		#sudo passwd gdm
		sudo usermod -a -G gdm gdm
		sudo usermod -a -G input gdm
		sudo usermod -a -G input $USER
		sudo usermod -a -G input usuario
		cd ../../../..
		sudo rm -r nwfermi*
		# Notificaciones al terminar
		#
		echo ""
		echo -e "${ROJO}Reinicie el equipo para que se ejecute la aplicación${NORMAL}"
		echo ""
		sudo notify-send "Reinicie el equipo para que se ejecute la aplicación"
		# Borrar los repositorios de git y archivos de instalación
		#
		cd ..
		sudo rm -r smartdre
		sleep 3
		exit
	
# Notificaciones al terminar
#
	echo ""
	echo -e "${ROJO}Reinicie el equipo para que se ejecute la aplicación${NORMAL}"
	echo ""
	sudo notify-send "Reinicie el equipo para que se ejecute la aplicación"
	echo ""
	echo -e "${ROJO}No funcionará el táctil si el PC y proyector tienen resolución diferente${NORMAL}"
	echo ""
	sudo notify-send "No funcionará el táctil si el PC y proyector tienen resolución diferente"
	
# Borrar los repositorios de git y archivos de instalación
#
	cd ..
	sudo rm -r smartdre
