#! /bin/bash

sudo rm ~/.config/autostart/smartdre.desktop

sudo docker stop smartboard

sudo docker rm smartboard

sudo docker stop smart

sudo docker rm smart

sudo docker stop testing

sudo docker rm testing

sudo docker rmi aosucas499/smartdre:testing

sudo docker rmi aosucas499/smartdre

sudo docker rmi aosucas499/smartdre:0.5

sudo docker rmi aosucas499/smartdre:0.4

sudo docker rmi aosucas499/smartdre:0.3

sudo docker rmi aosucas499/smartdre:0.2

sudo docker rmi aosucas499/smartdre:0.1

sudo docker rmi lliurex/lliurex-smart

sudo apt purge --remove nwfermi-daemon nwfermi-module xf86-input-nextwindow -y

sudo apt purge --remove zero-lliurex-smart lliurex-smart zero-lliurex-docker -y

sudo delgroup docker

sudo apt purge --remove docker-ce docker-ce-cli containerd.io -y
