#! /bin/bash

# Borrado de archivos anteriores de smartdre o lliurex-smart
#
echo ""
echo -e "${ROJO}Borrando antiguos archivos de smartdre o lliurex-smart${NORMAL}"
echo ""
echo -e "${ROJO}Deleting old files from smartdre or lliurex-smart${NORMAL}"
echo ""
sleep 3
##
#
sudo rm /etc/xdg/autostart/smartdre.desktop

sudo rm /usr/share/applications/smartdre.desktop

sudo rm /usr/share/applications/smartdre-controlpanel.desktop

sudo rm /usr/share/applications/smartdre-orient.desktop

sudo rm /usr/bin/smartdre

sudo rm /etc/sudoers.d/zz-smartdre

sudo rm /etc/xdg/autostart/zz-lliurex-smart.desktop

sudo rm /usr/share/applications/zz-lliurex-smart.desktop

sudo rm /etc/xdg/autostart/lliurex-smar*

sudo rm /usr/share/applications/lliurex-smar*

sudo rm /usr/bin/lliurex-smart

sudo docker stop smartboard

sudo docker rm smartboard

sudo docker stop smartboard-testing

sudo docker rm smartboard-testing

sudo docker stop smartboard-0.6

sudo docker rm smartboard-0.6

sudo docker stop smartboard-0.5

sudo docker rm smartboard-0.5

sudo docker stop smartboard-0.4

sudo docker rm smartboard-0.4

sudo docker stop smartboard-0.3

sudo docker rm smartboard-0.3

sudo docker stop smartboard-0.2

sudo docker rm smartboard-0.2

sudo docker stop smart

sudo docker rm smart

sudo docker stop testing

sudo docker rm testing

sudo docker rmi aosucas499/smartdre:testing

#sudo docker rmi aosucas499/smartdre

sudo docker rmi aosucas499/smartdre:0.6

sudo docker rmi aosucas499/smartdre:0.5

sudo docker rmi aosucas499/smartdre:0.4

sudo docker rmi aosucas499/smartdre:0.3

sudo docker rmi aosucas499/smartdre:0.2

sudo docker rmi aosucas499/smartdre:0.1

sudo docker rmi lliurex/lliurex-smart

sudo apt purge --remove nwfermi-daemon nwfermi-module nwfermi-module-host nwfermi-module-host-pointer xf86-input-nextwindow -y

dkms unbuild nwfermi/0.6.5.0 --all
dkms unbuild nwfermi/0.7.0.1 --all

sudo apt purge --remove zero-lliurex-smart lliurex-smart zero-lliurex-docker -y

sudo rm /etc/apt/sources.list.d/docker.list

#sudo delgroup docker

#sudo apt purge --remove docker-ce docker-ce-cli containerd.io -y
