#! /bin/bash

sudo rm ~/.config/autostart/smartdre.desktop

sudo docker stop smartboard

sudo docker rm smartboard

sudo docker rmi ed9c7f460069 

sudo apt purge --remove nwfermi-daemon nwfermi-module xf86-input-nextwindow -y

sudo apt purge --remove zero-lliurex-smart lliurex-smart zero-lliurex-docker -y

sudo delgroup docker

sudo apt purge --remove docker-ce docker-ce-cli containerd.io -y
